[2024-12-12T08:14:07.181+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-12T08:14:07.206+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_orchestrator.dbt_run_staging.dbt_run_stg_brand manual__2024-12-12T08:05:08.618053+00:00 [queued]>
[2024-12-12T08:14:07.216+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_orchestrator.dbt_run_staging.dbt_run_stg_brand manual__2024-12-12T08:05:08.618053+00:00 [queued]>
[2024-12-12T08:14:07.216+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-12-12T08:14:07.229+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run_staging.dbt_run_stg_brand> on 2024-12-12 08:05:08.618053+00:00
[2024-12-12T08:14:07.234+0000] {standard_task_runner.py:63} INFO - Started process 407 to run task
[2024-12-12T08:14:07.237+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_orchestrator', 'dbt_run_staging.dbt_run_stg_brand', 'manual__2024-12-12T08:05:08.618053+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpgtd3absi']
[2024-12-12T08:14:07.239+0000] {standard_task_runner.py:91} INFO - Job 164: Subtask dbt_run_staging.dbt_run_stg_brand
[2024-12-12T08:14:07.282+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_orchestrator.dbt_run_staging.dbt_run_stg_brand manual__2024-12-12T08:05:08.618053+00:00 [running]> on host 34fdc836a0bb
[2024-12-12T08:14:07.365+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ma7moud' AIRFLOW_CTX_DAG_ID='dbt_orchestrator' AIRFLOW_CTX_TASK_ID='dbt_run_staging.dbt_run_stg_brand' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T08:05:08.618053+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T08:05:08.618053+00:00'
[2024-12-12T08:14:07.365+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-12T08:14:07.377+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-12T08:14:07.378+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/ecommerce --models models/staging/stg_brand']
[2024-12-12T08:14:07.390+0000] {subprocess.py:86} INFO - Output:
[2024-12-12T08:14:09.349+0000] {subprocess.py:93} INFO - [0m08:14:09  Running with dbt=1.8.0
[2024-12-12T08:14:09.671+0000] {subprocess.py:93} INFO - [0m08:14:09  Registered adapter: postgres=1.8.0
[2024-12-12T08:14:10.083+0000] {subprocess.py:93} INFO - [0m08:14:10  Unable to do partial parsing because a project config has changed
[2024-12-12T08:14:11.237+0000] {subprocess.py:93} INFO - [0m08:14:11  Encountered an error:
[2024-12-12T08:14:11.237+0000] {subprocess.py:93} INFO - Compilation Error
[2024-12-12T08:14:11.237+0000] {subprocess.py:93} INFO -   Snapshot 'snapshot.ecommerce.CDC_product' (snapshots/CDC_product.sql) depends on a source named 'ecommerce_oltp.products' which was not found
[2024-12-12T08:14:12.250+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-12T08:14:12.251+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-12T08:14:12.266+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-12T08:14:12.269+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_orchestrator, task_id=dbt_run_staging.dbt_run_stg_brand, run_id=manual__2024-12-12T08:05:08.618053+00:00, execution_date=20241212T080508, start_date=20241212T081407, end_date=20241212T081412
[2024-12-12T08:14:12.287+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 164 for task dbt_run_staging.dbt_run_stg_brand (Bash command failed. The command returned a non-zero exit code 2.; 407)
[2024-12-12T08:14:12.300+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-12T08:14:12.329+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-12T08:14:12.335+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
